kind: pipeline
name: deploy

clone:
  git:
    image: plugins/git
    recursive: true
    submodule_update_remote: true
    submodule_override:
      themes/2019: http://git.chillidonut.com/grrowl/hugo-2019.git

trigger:
  branch:
  - master

steps:
- name: hugo
  image: monachus/hugo:v0.58.3
  commands:
  - hugo --gc --minify
- name: upload
  image: plugins/gcs
  settings:
    source: public/
    target: chillidonut.com/
    gzip: js,css,html
    cache_control: public,max-age=3600
    token:
      from_secret: deploy-token
