name: chillidonut
highlighter: pygments
gems: ['jekyll/minibundle']

# sass
sass:
  syntax: scss        # scss|sass
  style:  nested  # nested|expanded|compact|compressed

minibundle:
  minifier_commands:
    js: node_modules/.bin/uglifyjs --

collections:
  pages:
    output: true

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      path:         "pages"
      type:         pages
    values:
      layout:       "page"

mwehehe:
  - ヽ(⌐■_■)ノ♪♬
  - ┬━┬ノ(▀̿̿Ĺ̯̿̿▀̿ ̿ノ)
  - (つ•̀ᴥ•́)つ*:･ﾟ✧
  - (^ ◕ᴥ◕ ^)
  - └(՞▃՞ └)
  - (╯ಠ‿ಠ)╯︵┻━┻
  - ༼ ºل͟º༼ ºل͟º༽
  - ( ರ Ĺ̯ ರೃ )


