name: chillidonut
highlighter: pygments
gems: ['jekyll/minibundle']
exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'vendor', 'README.md', 'LICENSE', 'package.json']
baseurl: /
asseturls: ['/assets']

# sass
sass:
  syntax: scss        # scss|sass
  style:  nested  # nested|expanded|compact|compressed

minibundle:
  minifier_commands:
    js: node_modules/.bin/uglifyjs --

collections:
  pages:
    output: true

defaults:
  -
    scope:
      type:         pages
    values:
      layout:       "page"

mwehehe:
  - ヽ(⌐■_■)ノ♪♬
  - ┬━┬ノ(▀̿̿Ĺ̯̿̿▀̿ ̿ノ)
  - (つ•̀ᴥ•́)つ*:･ﾟ✧
  - (^ ◕ᴥ◕ ^)
  - └(՞▃՞ └)
  - (╯ಠ‿ಠ)╯︵┻━┻
  - ༼ ºل͟º༼ ºل͟º༽
  - ( ರ Ĺ̯ ರೃ )
